version: '3.9'
services:
  jidou-backend:
    container_name: "jidou-backend"
    build:
      context: .
      tags:
        - "${AWS_TAG}:latest"
        - "jidou-backend:latest"
    ports:
      - "8080:8080"
    env_file: ".env"
    environment:
      - REGION=${REGION}