name: "Terraform Destroy"
on:
  schedule:
    - cron: "45 23 * * *"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'

env:
  TF_CLOUD_ORGANIZATION: "Kuraiji"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Jidou"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform destroy
        uses: dflook/terraform-destroy@v2
        with:
          path: ${{ env.CONFIG_DIRECTORY }}
          workspace: ${{ env.TF_WORKSPACE }}